import MaximumLength from "../../vendor/ckeditor5-maximum-length/index";
import "../../vendor/ckeditor5-maximum-length/index-editor.css";
import { StrapiMediaLib } from "./plugins/StrapiMediaLib";
import "ckeditor5/ckeditor5.css";

import "./styles/atlas.css";

import {
  SpecialCharactersMathematical,
  SpecialCharactersEssentials,
  SpecialCharactersCurrency,
  SpecialCharactersArrows,
  SpecialCharactersLatin,
  SpecialCharactersText,
  ImageTextAlternative,
  TableCellProperties,
  FontBackgroundColor,
  GeneralHtmlSupport,
  AccessibilityHelp,
  TableColumnResize,
  SpecialCharacters,
  ImageInsertViaUrl,
  TextTransformation,
  PasteFromOffice,
  TableProperties,
  ListProperties,
  HorizontalLine,
  BalloonToolbar,
  FindAndReplace,
  Strikethrough,
  CloudServices,
  RemoveFormat,
  TableToolbar,
  TableCaption,
  ImageCaption,
  ImageToolbar,
  BlockToolbar,
  Superscript,
  ImageUpload,
  ImageResize,
  IndentBlock,
  ImageInline,
  ImageStyle,
  MediaEmbed,
  BlockQuote,
  Essentials,
  Autoformat,
  FontFamily,
  ImageBlock,
  Alignment,
  Underline,
  CodeBlock,
  Subscript,
  FontColor,
  HtmlEmbed,
  LinkImage,
  Paragraph,
  Highlight,
  WordCount,
  AutoImage,
  SelectAll,
  TodoList,
  Markdown,
  FontSize,
  AutoLink,
  Autosave,
  Heading,
  Indent,
  Italic,
  Table,
  Style,
  Title,
  Link,
  Bold,
  Code,
  List,
  Undo,
} from "ckeditor5";

// const CKEDITOR_BASE_CONFIG_FOR_PRESETS = {
//   light: {
//     plugins: [
//       Autoformat,
//       Bold,
//       Italic,
//       Essentials,
//       Heading,
//       Image,
//       ImageCaption,
//       ImageStyle,
//       ImageToolbar,
//       ImageUpload,
//       Indent,
//       Link,
//       List,
//       Paragraph,
//       PasteFromOffice,
//       Table,
//       TableToolbar,
//       TableColumnResize,
//       TableCaption,
//       WordCount,
//       StrapiMediaLib,
//     ],
//     toolbar: [
//       "undo",
//       "redo",
//       "|",
//       "heading",
//       "|",
//       "bold",
//       "italic",
//       "|",
//       "link",
//       "strapiMediaLib",
//       "insertTable",
//       "|",
//       "bulletedList",
//       "numberedList",
//     ],
//     heading: {
//       options: [
//         {
//           model: "paragraph",
//           title: "Paragraph",
//           class: "ck-heading_paragraph",
//         },
//         {
//           model: "heading1",
//           view: "h1",
//           title: "Heading 1",
//           class: "ck-heading_heading1",
//         },
//         {
//           model: "heading2",
//           view: "h2",
//           title: "Heading 2",
//           class: "ck-heading_heading2",
//         },
//         {
//           model: "heading3",
//           view: "h3",
//           title: "Heading 3",
//           class: "ck-heading_heading3",
//         },
//         {
//           model: "heading4",
//           view: "h4",
//           title: "Heading 4",
//           class: "ck-heading_heading4",
//         },
//       ],
//     },
//     image: {
//       toolbar: [
//         "imageStyle:inline",
//         "imageStyle:block",
//         "imageStyle:side",
//         "|",
//         "toggleImageCaption",
//         "imageTextAlternative",
//       ],
//     },
//     table: {
//       contentToolbar: [
//         "tableColumn",
//         "tableRow",
//         "mergeTableCells",
//         "|",
//         "toggleTableCaption",
//       ],
//     },
//   },

//   standard: {
//     plugins: [
//       Autoformat,
//       Bold,
//       Italic,
//       BlockQuote,
//       CodeBlock,
//       Essentials,
//       Heading,
//       Image,
//       ImageCaption,
//       ImageStyle,
//       ImageToolbar,
//       ImageUpload,
//       Indent,
//       Link,
//       LinkImage,
//       List,
//       MediaEmbed,
//       Paragraph,
//       PasteFromOffice,
//       Table,
//       TableToolbar,
//       TableColumnResize,
//       TableCaption,
//       WordCount,
//       StrapiMediaLib,
//     ],
//     toolbar: [
//       "undo",
//       "redo",
//       "|",
//       "heading",
//       "|",
//       "bold",
//       "italic",
//       "|",
//       "link",
//       "strapiMediaLib",
//       "mediaEmbed",
//       "blockQuote",
//       "insertTable",
//       "codeBlock",
//       "|",
//       "bulletedList",
//       "numberedList",
//       "outdent",
//       "indent",
//     ],
//     heading: {
//       options: [
//         {
//           model: "paragraph",
//           title: "Paragraph",
//           class: "ck-heading_paragraph",
//         },
//         {
//           model: "heading1",
//           view: "h1",
//           title: "Heading 1",
//           class: "ck-heading_heading1",
//         },
//         {
//           model: "heading2",
//           view: "h2",
//           title: "Heading 2",
//           class: "ck-heading_heading2",
//         },
//         {
//           model: "heading3",
//           view: "h3",
//           title: "Heading 3",
//           class: "ck-heading_heading3",
//         },
//         {
//           model: "heading4",
//           view: "h4",
//           title: "Heading 4",
//           class: "ck-heading_heading4",
//         },
//       ],
//     },
//     image: {
//       toolbar: [
//         "imageStyle:inline",
//         "imageStyle:block",
//         "imageStyle:side",
//         "|",
//         "toggleImageCaption",
//         "imageTextAlternative",
//         "|",
//         "linkImage",
//       ],
//     },
//     table: {
//       contentToolbar: [
//         "tableColumn",
//         "tableRow",
//         "mergeTableCells",
//         "|",
//         "toggleTableCaption",
//       ],
//     },
//   },

//   mediaEmbed: {
//     previewsInData: false,
//     previewsInData: true,
//   },

//   rich: {
//     plugins: [
//       // Alignment,
//       Autoformat,
//       Bold,
//       Italic,
//       Underline,
//       Strikethrough,
//       Code,
//       Subscript,
//       Superscript,
//       BlockQuote,
//       CodeBlock,
//       Essentials,
//       FontSize,
//       FontFamily,
//       FontColor,
//       FontBackgroundColor,
//       FindAndReplace,
//       Heading,
//       HorizontalLine,
//       HtmlEmbed,
//       Image,
//       ImageCaption,
//       ImageStyle,
//       ImageToolbar,
//       ImageUpload,
//       ImageResize,
//       Indent,
//       IndentBlock,
//       Link,
//       LinkImage,
//       List,
//       ListProperties,
//       TodoList,
//       MediaEmbed,
//       Paragraph,
//       PasteFromOffice,
//       RemoveFormat,
//       SpecialCharacters,
//       SpecialCharactersEssentials,
//       Table,
//       TableToolbar,
//       TableProperties,
//       TableCellProperties,
//       TableColumnResize,
//       TableCaption,
//       WordCount,
//       Highlight,
//       StrapiMediaLib,
//     ],
//     toolbar: {
//       items: [
//         "undo",
//         "redo",
//         "|",
//         "findAndReplace",
//         "selectAll",
//         "|",
//         "heading",
//         "|",
//         "fontSize",
//         "fontFamily",
//         "fontColor",
//         "fontBackgroundColor",
//         "|",
//         "bold",
//         "italic",
//         "underline",
//         "strikethrough",
//         "superscript",
//         "subscript",
//         "code",
//         "removeFormat",
//         "-",
//         "link",
//         "strapiMediaLib",
//         "mediaEmbed",
//         "insertTable",
//         "horizontalLine",
//         "blockQuote",
//         "codeBlock",
//         "htmlEmbed",
//         "specialCharacters",
//         "highlight",
//         "|",
//         "alignment",
//         "|",
//         "bulletedList",
//         "numberedList",
//         "todoList",
//         "outdent",
//         "indent",
//       ],
//       shouldNotGroupWhenFull: true,
//     },
//     heading: {
//       options: [
//         {
//           model: "paragraph",
//           title: "Paragraph",
//           class: "ck-heading_paragraph",
//         },
//         {
//           model: "heading1",
//           view: "h1",
//           title: "Heading 1",
//           class: "ck-heading_heading1",
//         },
//         {
//           model: "heading2",
//           view: "h2",
//           title: "Heading 2",
//           class: "ck-heading_heading2",
//         },
//         {
//           model: "heading3",
//           view: "h3",
//           title: "Heading 3",
//           class: "ck-heading_heading3",
//         },
//         {
//           model: "heading4",
//           view: "h4",
//           title: "Heading 4",
//           class: "ck-heading_heading4",
//         },
//       ],
//     },
//     list: {
//       properties: {
//         styles: true,
//         startIndex: true,
//         reversed: true,
//       },
//     },
//     image: {
//       resizeUnit: "%",
//       resizeOptions: [
//         {
//           name: "resizeImage:original",
//           value: null,
//           icon: "original",
//         },
//         {
//           name: "resizeImage:25",
//           value: "25",
//           icon: "small",
//         },
//         {
//           name: "resizeImage:50",
//           value: "50",
//           icon: "medium",
//         },
//         {
//           name: "resizeImage:75",
//           value: "75",
//           icon: "large",
//         },
//       ],
//       toolbar: [
//         "imageStyle:inline",
//         "imageStyle:block",
//         "imageStyle:side",
//         "|",
//         "toggleImageCaption",
//         "imageTextAlternative",
//         "|",
//         "linkImage",
//         "|",
//         "resizeImage:25",
//         "resizeImage:50",
//         "resizeImage:75",
//         "resizeImage:original",
//       ],
//     },
//     table: {
//       contentToolbar: [
//         "tableColumn",
//         "tableRow",
//         "mergeTableCells",
//         "|",
//         "tableCellProperties",
//         "tableProperties",
//         "|",
//         "toggleTableCaption",
//       ],
//     },
//     fontSize: {
//       options: [9, 11, 13, "default", 17, 19, 21, 27, 35],
//       supportAllValues: false,
//     },
//     fontFamily: {
//       options: [
//         "default",
//         "Arial, Helvetica Neue, Helvetica, Source Sans Pro, sans-serif",
//         "Courier New, Courier, monospace",
//         "Georgia, serif",
//         "Lucida Sans Unicode, Lucida Grande, sans-serif",
//         "Tahoma, Geneva, sans-serif",
//         "Times New Roman, Times, serif",
//         "Trebuchet MS, Helvetica, sans-serif",
//         "Verdana, Geneva, sans-serif",
//         "Roboto, Roboto Black, Roboto Medium, Roboto Light, sans-serif",
//       ],
//       supportAllValues: true,
//     },
//     fontColor: {
//       columns: 5,
//       documentColors: 10,
//     },
//     fontBackgroundColor: {
//       columns: 5,
//       documentColors: 10,
//     },
//   },
// };

const ATLAS_CKEDITOR_CONFIG = {
  toolbar: {
    items: [
      "undo",
      "redo",
      "|",
      "findAndReplace",
      "|",
      "heading",
      "style",
      "|",
      "fontSize",
      "fontFamily",
      "fontColor",
      "fontBackgroundColor",
      "|",
      "bold",
      "italic",
      "underline",
      "strikethrough",
      "subscript",
      "superscript",
      "code",
      "removeFormat",
      "|",
      "specialCharacters",
      "horizontalLine",
      "link",
      "mediaEmbed",
      "insertTable",
      "highlight",
      "blockQuote",
      "codeBlock",
      "htmlEmbed",
      "|",
      "alignment",
      "|",
      "bulletedList",
      "numberedList",
      "todoList",
      "outdent",
      "indent",
    ],
    shouldNotGroupWhenFull: false,
  },
  plugins: [
    AccessibilityHelp,
    Alignment,
    Autoformat,
    AutoImage,
    AutoLink,
    Autosave,
    BalloonToolbar,
    BlockQuote,
    BlockToolbar,
    Bold,
    CloudServices,
    Code,
    CodeBlock,
    Essentials,
    FindAndReplace,
    FontBackgroundColor,
    FontColor,
    FontFamily,
    FontSize,
    GeneralHtmlSupport,
    Heading,
    Highlight,
    HorizontalLine,
    HtmlEmbed,
    ImageBlock,
    ImageCaption,
    ImageInline,
    ImageInsertViaUrl,
    ImageResize,
    ImageStyle,
    ImageTextAlternative,
    ImageToolbar,
    ImageUpload,
    Indent,
    IndentBlock,
    Italic,
    Link,
    LinkImage,
    List,
    ListProperties,
    MediaEmbed,
    Paragraph,
    PasteFromOffice,
    RemoveFormat,
    SelectAll,
    SpecialCharacters,
    SpecialCharactersArrows,
    SpecialCharactersCurrency,
    SpecialCharactersEssentials,
    SpecialCharactersLatin,
    SpecialCharactersMathematical,
    SpecialCharactersText,
    Strikethrough,
    Style,
    Subscript,
    Superscript,
    Table,
    TableCaption,
    TableCellProperties,
    TableColumnResize,
    TableProperties,
    TableToolbar,
    TextTransformation,
    Title,
    TodoList,
    Underline,
    Undo,
    // Atlas Stuff
    WordCount,
    StrapiMediaLib,
  ],
  balloonToolbar: [
    "bold",
    "italic",
    "|",
    "link",
    "|",
    "bulletedList",
    "numberedList",
  ],
  blockToolbar: [
    "fontSize",
    "fontColor",
    "fontBackgroundColor",
    "|",
    "bold",
    "italic",
    "|",
    "link",
    "strapiMediaLib",
    "insertTable",
    "|",
    "bulletedList",
    "numberedList",
    "outdent",
    "indent",
  ],
  fontFamily: {
    supportAllValues: true,
  },
  fontSize: {
    options: [10, 12, 14, "default", 18, 20, 22],
    supportAllValues: true,
  },
  heading: {
    options: [
      {
        model: "paragraph",
        title: "Paragraph",
        class: "ck-heading_paragraph",
      },
      {
        model: "heading1",
        view: "h1",
        title: "Heading 1",
        class: "ck-heading_heading1",
      },
      {
        model: "heading2",
        view: "h2",
        title: "Heading 2",
        class: "ck-heading_heading2",
      },
      {
        model: "heading3",
        view: "h3",
        title: "Heading 3",
        class: "ck-heading_heading3",
      },
      {
        model: "heading4",
        view: "h4",
        title: "Heading 4",
        class: "ck-heading_heading4",
      },
      {
        model: "heading5",
        view: "h5",
        title: "Heading 5",
        class: "ck-heading_heading5",
      },
      {
        model: "heading6",
        view: "h6",
        title: "Heading 6",
        class: "ck-heading_heading6",
      },
    ],
  },
  htmlSupport: {
    allow: [
      {
        name: /^.*$/,
        styles: true,
        attributes: true,
        classes: true,
      },
    ],
  },
  image: {
    toolbar: [
      "toggleImageCaption",
      "imageTextAlternative",
      "|",
      "imageStyle:inline",
      "imageStyle:wrapText",
      "imageStyle:breakText",
      "|",
      "resizeImage",
    ],
  },
  initialData:
    '<h2>Congratulations on setting up CKEditor 5! 🎉</h2>\n<p>\n    You\'ve successfully created a CKEditor 5 project. This powerful text editor will enhance your application, enabling rich text editing\n    capabilities that are customizable and easy to use.\n</p>\n<h3>What\'s next?</h3>\n<ol>\n    <li>\n        <strong>Integrate into your app</strong>: time to bring the editing into your application. Take the code you created and add to your\n        application.\n    </li>\n    <li>\n        <strong>Explore features:</strong> Experiment with different plugins and toolbar options to discover what works best for your needs.\n    </li>\n    <li>\n        <strong>Customize your editor:</strong> Tailor the editor\'s configuration to match your application\'s style and requirements. Or even\n        write your plugin!\n    </li>\n</ol>\n<p>\n    Keep experimenting, and don\'t hesitate to push the boundaries of what you can achieve with CKEditor 5. Your feedback is invaluable to us\n    as we strive to improve and evolve. Happy editing!\n</p>\n<h3>Helpful resources</h3>\n<ul>\n    <li>📝 <a href="https://orders.ckeditor.com/trial/premium-features">Trial sign up</a>,</li>\n    <li>📕 <a href="https://ckeditor.com/docs/ckeditor5/latest/installation/index.html">Documentation</a>,</li>\n    <li>⭐️ <a href="https://github.com/ckeditor/ckeditor5">GitHub</a> (star us if you can!),</li>\n    <li>🏠 <a href="https://ckeditor.com">CKEditor Homepage</a>,</li>\n    <li>🧑‍💻 <a href="https://ckeditor.com/ckeditor-5/demo/">CKEditor 5 Demos</a>,</li>\n</ul>\n<h3>Need help?</h3>\n<p>\n    See this text, but the editor is not starting up? Check the browser\'s console for clues and guidance. It may be related to an incorrect\n    license key if you use premium features or another feature-related requirement. If you cannot make it work, file a GitHub issue, and we\n    will help as soon as possible!\n</p>\n',
  link: {
    addTargetToExternalLinks: true,
    defaultProtocol: "https://",
    decorators: {
      toggleDownloadable: {
        mode: "manual",
        label: "Downloadable",
        attributes: {
          download: "file",
        },
      },
    },
  },
  list: {
    properties: {
      styles: true,
      startIndex: true,
      reversed: true,
    },
  },
  placeholder: "Type or paste your content here!",
  style: {
    definitions: [
      {
        name: "Article category",
        element: "h3",
        classes: ["category"],
      },
      {
        name: "Title",
        element: "h2",
        classes: ["document-title"],
      },
      {
        name: "Subtitle",
        element: "h3",
        classes: ["document-subtitle"],
      },
      {
        name: "Info box",
        element: "p",
        classes: ["info-box"],
      },
      {
        name: "Side quote",
        element: "blockquote",
        classes: ["side-quote"],
      },
      {
        name: "Marker",
        element: "span",
        classes: ["marker"],
      },
      {
        name: "Spoiler",
        element: "span",
        classes: ["spoiler"],
      },
      {
        name: "Code (dark)",
        element: "pre",
        classes: ["fancy-code", "fancy-code-dark"],
      },
      {
        name: "Code (bright)",
        element: "pre",
        classes: ["fancy-code", "fancy-code-bright"],
      },
    ],
  },
  table: {
    contentToolbar: [
      "tableColumn",
      "tableRow",
      "mergeTableCells",
      "tableProperties",
      "tableCellProperties",
    ],
  },
};

export default class Configurator {
  constructor(fieldConfig) {
    this.fieldConfig = fieldConfig;
  }

  getEditorConfig() {
    const config = this._getBaseConfig();

    const maxLength = this.fieldConfig.maxLength;
    const outputOption = this.fieldConfig.options.output;

    if (outputOption === "Markdown") {
      config.plugins.push(Markdown);
    }

    if (maxLength) {
      config.plugins.push(MaximumLength);

      config.maximumLength = {
        characters: maxLength,
      };
    }

    return config;
  }

  _getBaseConfig() {
    return ATLAS_CKEDITOR_CONFIG;
  }

  // _getBaseConfig() {
  //   const presetName = this.fieldConfig.options.preset;

  //   switch (presetName) {
  //     case "light":
  //       return CKEDITOR_BASE_CONFIG_FOR_PRESETS.light;
  //     case "standard":
  //       return CKEDITOR_BASE_CONFIG_FOR_PRESETS.standard;
  //     case "rich":
  //       return CKEDITOR_BASE_CONFIG_FOR_PRESETS.rich;
  //     default:
  //       throw new Error("Invalid preset name " + presetName);
  //   }
  // }
}
